<?php

namespace Proxies\__CG__\sprint2\RealEstate\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \sprint2\RealEstate\AdminBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'mail', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'password', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'nummobile', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'numfix', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'statusMatrimonial', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'role', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'urlp', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'image');
        }

        return array('__isInitialized__', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'mail', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'password', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'nummobile', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'numfix', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'statusMatrimonial', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'role', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'urlp', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Utilisateur' . "\0" . 'image');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', array($mail));

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', array());

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNummobile($nummobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNummobile', array($nummobile));

        return parent::setNummobile($nummobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getNummobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNummobile', array());

        return parent::getNummobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumfix($numfix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumfix', array($numfix));

        return parent::setNumfix($numfix);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumfix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumfix', array());

        return parent::getNumfix();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusMatrimonial($statusMatrimonial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusMatrimonial', array($statusMatrimonial));

        return parent::setStatusMatrimonial($statusMatrimonial);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusMatrimonial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusMatrimonial', array());

        return parent::getStatusMatrimonial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', array($role));

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array());

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlp($urlp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlp', array($urlp));

        return parent::setUrlp($urlp);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlp', array());

        return parent::getUrlp();
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

}
