sprint2\realEstateBundle\Entity\Offre:
    properties:
        etat:
            - NotEqualTo:
                value: -1
        typeimmob:
            - NotEqualTo:
                value: -1
        