<?php

namespace Proxies\__CG__\sprint2\RealEstate\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Boitemessages extends \sprint2\RealEstate\AdminBundle\Entity\Boitemessages implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'id', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'contenu', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'vu', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'tempsEnvoi', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'idDestinataire', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'idExpediteur');
        }

        return array('__isInitialized__', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'id', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'contenu', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'vu', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'tempsEnvoi', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'idDestinataire', '' . "\0" . 'sprint2\\RealEstate\\AdminBundle\\Entity\\Boitemessages' . "\0" . 'idExpediteur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Boitemessages $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu($contenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', array($contenu));

        return parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', array());

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setVu($vu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVu', array($vu));

        return parent::setVu($vu);
    }

    /**
     * {@inheritDoc}
     */
    public function getVu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVu', array());

        return parent::getVu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempsEnvoi($tempsEnvoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempsEnvoi', array($tempsEnvoi));

        return parent::setTempsEnvoi($tempsEnvoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempsEnvoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempsEnvoi', array());

        return parent::getTempsEnvoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDestinataire(\sprint2\RealEstate\AdminBundle\Entity\Utilisateur $idDestinataire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDestinataire', array($idDestinataire));

        return parent::setIdDestinataire($idDestinataire);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDestinataire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDestinataire', array());

        return parent::getIdDestinataire();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdExpediteur(\sprint2\RealEstate\AdminBundle\Entity\Utilisateur $idExpediteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdExpediteur', array($idExpediteur));

        return parent::setIdExpediteur($idExpediteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdExpediteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdExpediteur', array());

        return parent::getIdExpediteur();
    }

}
