sprint2\RealEstate\AdminBundle\Entity\Agence:
    type: entity
    table: agence
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
        idGerant:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_gerant
    fields:
        idAdresse:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_adresse
        nom:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        description:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
