Archive:
    type: entity
    table: archive
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idGerant:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_gerant
        date:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        url:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
